#define HPADDING 2
#define VPADDING 1
#define RIGHT_COL_X (WINLOC_FIELD_X + WINDIM_FIELD_X + HPADDING)
#define RIGHT_COL_WIDTH (2 + game.block_size.x * TM_SIZE)

#define WINLOC_FIELD_X 0
#define WINLOC_FIELD_Y 0 
#define WINDIM_FIELD_X (2 + game.block_size.x * FIELD_X)
#define WINDIM_FIELD_Y (2 + game.block_size.y * (FIELD_Y - 1))

#define WINLOC_HOLDTM_X RIGHT_COL_X
#define WINLOC_HOLDTM_Y 0
#define WINDIM_HOLDTM_X RIGHT_COL_WIDTH 
#define WINDIM_HOLDTM_Y (2 + game.block_size.y * TM_SIZE)

#define WINLOC_NEXTTM_X RIGHT_COL_X 
#define WINLOC_NEXTTM_Y (WINLOC_HOLDTM_Y + WINDIM_HOLDTM_Y + VPADDING)
#define WINDIM_NEXTTM_X RIGHT_COL_WIDTH
#define WINDIM_NEXTTM_Y (2 + game.block_size.y * TM_SIZE)

#define WINLOC_LEVEL_X RIGHT_COL_X
#define WINLOC_LEVEL_Y (WINLOC_NEXTTM_Y + WINDIM_NEXTTM_Y + VPADDING)
#define WINDIM_LEVEL_X RIGHT_COL_WIDTH
#define WINDIM_LEVEL_Y (2 + 1)

#define WINLOC_SCORE_X RIGHT_COL_X
#define WINLOC_SCORE_Y (WINLOC_LEVEL_Y + WINDIM_LEVEL_Y + VPADDING)
#define WINDIM_SCORE_X 2 + 10 > RIGHT_COL_WIDTH ? 12 : RIGHT_COL_WIDTH
#define WINDIM_SCORE_Y (2 + 1)


